travis:
  secure:
    BINSTAR_TOKEN: WQFtE9K8gpfRfMZa6pVi6AW4rDVQi0HTF6U81jEpCIOsBtVOkKjiZARJ+hqoI97XMhG4gh8l3Tpnjl0+F/ADVtdX/a/ppBi67d6VbTwKlg6N53hM026dlTY8jKnCF+bluCkY5AKQyHgAYEWSMP+2ZKVyLE+x3SGOwkflL16vBCCYjco5jqj42qN7qQUGOQyZAS9Nc3Rg3u6gMxW04NoIOLR10+OSlEDJCNCcWsbucpsoownJqirm5qNOUqpvXGVWvR7IQV+DYZJogWRSt4SqpXg9e0oq9RIUNP3bH+6o+UhtdeHIETI/p4HHw/7DZxx6cghd85r4q8vJxKp64Af2KaazC20AHg/KVuvItlhf+GGgdgQLXHDX4A2rxxWHGrcvNyB+B9BQ98d2FtVkk7OuoZ7gViDtSXta58NHbDadNmfETjt3/F3i5E/M6dkt8dh1aPxvoiHEbkZBy30GNbqEf/Chm3kkRYu/b5GLlCz3IMYSnx27AOkzxROE+PzpnBNGm2FcJ8zpnNag8DCDby1pKxPxrDLHTjqqfRc3TMY197pipeXmWZ6fjGQMItjGhD6j22jyLL74KqCAhzOnnrWRY0ncuFiYOYqaHVBcpLMpGN+vfo+n5CggF8gKJE4XLgfg/DudUQ4gURAkQUV0gX5th+ORfIh9Q04QY0sEqA9q7Rg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
  linux_ppc64le: default
  linux_aarch64: default
